### PR TITLE
VB.NET Version

### PR DESCRIPTION
**Pull request by jefhtavares**

### CODE REVIEW

**Comment by mememori** [comment]
Nice train! :+1:

**Comment by haskellcamargo** [comment]
@mememori, I believe we have 2 VisualBasic implementations in different folders. Can you check, please, and, if true, correctly allocate them in versions?

**Comment by mememori** [comment]
After taking a look at the code, it is clear that both implementations of vb are vb.net.

So, i raise a question: @mabrasil, @haskellcamargo shall we consider vb6 and vbnet implementations to be the same language ?

Also, shall the vbnet implementation folder be `vb.net`, `vbnet` or `visualbasic` (in the last case, we consider both vbnet and vb6 to be the same thing) ?
After we decide on this, i'll do a PR to allocate both implementations to the same folder

**Comment by Kuchiriel** [comment]
I have wrote a vb.net version, but the author has labeled the language as "visual basic", so i put there.

**Pull request merged**
